export const ErrorCode = {
  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // General
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Conflict / Idempotency
  CONFLICT: 'CONFLICT',
  IDEMPOTENCY_VIOLATION: 'IDEMPOTENCY_VIOLATION',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  OPTIMISTIC_LOCK_FAILED: 'OPTIMISTIC_LOCK_FAILED',

  // Billing
  ALREADY_PAID: 'ALREADY_PAID',
  BILL_CANCELLED: 'BILL_CANCELLED',
  BILL_NOT_PAYABLE: 'BILL_NOT_PAYABLE',
  MAX_RETRIES_EXCEEDED: 'MAX_RETRIES_EXCEEDED',

  // Account
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',

  // Meter
  METER_INACTIVE: 'METER_INACTIVE',

  // Outage
  OUTAGE_ALREADY_RESOLVED: 'OUTAGE_ALREADY_RESOLVED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
